In [1]:
import numpy as np

1 Write a NumPy program to get the numpy version and show numpy build configuration.

In [8]:
print(np.version.version)
#print(np.show_config())

1.15.1


2 Write a NumPy program to  get help on the add function.

In [11]:
#print(np.info(np.add))

3 Write a NumPy program to test whether none of the elements of a given array is zero

In [17]:
y = np.arange(0,10)
print(y)
print(np.all(y))
x = np.arange(1,10)
print(x)
print(np.all(x))

[0 1 2 3 4 5 6 7 8 9]
False
[1 2 3 4 5 6 7 8 9]
True


4 Write a NumPy program to test if any of the elements of a given array is non-zero.

y = np.arange(0,10)
print(y)
print(np.any(y))
x = np.zeros(10)
print(x)
print(np.any(x))

5 Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [38]:
y = np.array([4, -1, np.nan, np.inf])
print(y)
print(np.isfinite(y))

[ 4. -1. nan inf]
[ True  True False False]


6 Write a NumPy program to test element-wise for positive or negative infinity. 

In [39]:
y = np.array([-np.inf, 4, -1, np.nan, np.inf])
print(y)
print(np.isinf(y))

[-inf   4.  -1.  nan  inf]
[ True False False False  True]


7 Write a NumPy program to test element-wise for NaN of a given array.

In [40]:
y = np.array([-np.inf, 4, -1, np.nan])
print(y)
print(np.isnan(y))

[-inf   4.  -1.  nan]
[False False False  True]


8 Write a NumPy program to test element-wise for complex number, real number of a given array. Also test if a given number is a scalar type or not.

In [53]:
y = np.array([4, -1, 0, np.nan, 2j])
print(y)
print(np.iscomplex(y))
print(np.isreal(y))
print(np.isscalar(2.1))
print(np.isscalar([2.1]))

[ 4.+0.j -1.+0.j  0.+0.j nan+0.j  0.+2.j]
[False False False False  True]
[ True  True  True  True False]
True
False


9 Write a NumPy program to test if two arrays are element-wise equal within a tolerance. 

In [54]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

False
True
False
False
True


10 Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays. 

x = np.array([3, 5, 7])
y = np.array([2, 5, 6])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

12 Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 

In [74]:
y = np.array([1,7,13,105])
print(y)
print("bytes of memory: {} bytes".format(y.size*y.itemsize))

[  1   7  13 105]
bytes of memory: 16 bytes


 13 Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives. 

In [82]:
y = np.zeros(10)
y = np.append(y, np.ones(10))
y = np.append(y, np.full(10, 5))
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


14 Write a NumPy program to create an array of the integers from 30 to70

In [84]:
y = np.arange(30,71)
print(y)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


15 Write a NumPy program to create an array of all the even integers from 30 to 70.

In [86]:
y = np.arange(30,71,2)
print(y)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


16 Write a NumPy program to create a 3x3 identity matrix.

In [88]:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


17 Write a NumPy program to generate a random number between 0 and 1.

In [94]:
# numpy.random.normal(mean, std, size)¶
y = np.random.normal(0,1,1)
print(y)

[0.14405393]


18 Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [98]:
y = np.random.normal(0,1,15)
print(y)

[-0.43993281  0.14253163  0.79071451 -0.40191813  0.54042709  0.52643179
  1.91179937  0.49478018 -0.66100353  0.35814784  0.49661388 -0.58869612
 -0.84166219  0.71084827 -0.99494737]


19 Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last. 

In [101]:
y = np.arange(15,56)
print(y[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


20 Write a NumPy program to create a 3X4 array using and iterate over it.

In [106]:
y = np.arange(1,13).reshape(3,4)
print(y)
for x in np.nditer(y):
  print(x,end="+")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1+2+3+4+5+6+7+8+9+10+11+12+

21 Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [110]:
y = np.linspace(5,50, 10)
print(y)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


22 Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [118]:
y = np.arange(0,21)
print(y)
y[(y>8)&(y<16)]*= -1
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


23 Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10. 

In [121]:
y = np.random.randint(0,11,5)
print(y)

[9 1 5 0 4]


24 Write a NumPy program to multiply the values of two given vectors.

In [128]:
y = np.random.randint(0,11,6).reshape(2,3)
x = np.random.randint(0,11,6).reshape(2,3)
print(y)
print()
print(x)
print()
print(y*x)

[[ 1  1  7]
 [10  7  0]]

[[9 8 1]
 [8 2 1]]

[[ 9  8  7]
 [80 14  0]]


25 Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [129]:
y = np.arange(10,22).reshape(3,4)
print(y)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


26 Write a NumPy program to find the number of rows and columns of a given matrix.

In [135]:
y = np.arange(10,22).reshape(3,4)
print("{} rows".format(np.size(y, axis=0)))
print ("{} columns".format(np.size(y, axis=1)))
print(y.shape)

3 rows
4 columns
(3, 4)


27 Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0. 

In [136]:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


28 Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [157]:
y = np.ones((10,10))
y[1:,1:-1]=0
print(y)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


29 Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [167]:
y = np.diag([1,2,3,4,5]) 
print(y)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


30 Write a NumPy program to create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. 

In [185]:
y = np.zeros((4,4))
y[::2, 1::2]=1
y[1::2,::2]=1
print(y)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


31 Write a NumPy program to create a 3x3x3 array filled with arbitrary values

In [186]:
y = np.random.random((3,3,3))
print(y)

[[[0.98867963 0.02229318 0.4288399 ]
  [0.56519902 0.85405336 0.88915494]
  [0.71185821 0.18788512 0.71861521]]

 [[0.18958179 0.60840344 0.80816281]
  [0.27391239 0.40519775 0.06431563]
  [0.27201174 0.9073688  0.00348589]]

 [[0.93162309 0.3694225  0.4300489 ]
  [0.40091472 0.9793532  0.20743704]
  [0.62487184 0.20500224 0.09592594]]]


32 Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of an given array.

In [205]:
y = np.arange(1,11).reshape(5,2)
print(y)
print(np.sum(y))
print("sum of rows:",np.sum(y, axis=1))
print("sum of columns", np.sum(y, axis=0))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
55
sum of rows: [ 3  7 11 15 19]
sum of columns [25 30]


33 Write a NumPy program to compute the inner product of two given vectors. Go 

In [216]:
y = np.array([3,5])
x = np.array([1,2])
print(np.dot(x,y))

13


34 Write a NumPy program to add a vector to each row of a given matrix.

In [234]:
y = np.arange(3,13).reshape(2,5)
print(y)
x = np.array([1,2,3,4,5])
print(y.shape[0])
summed = np.empty_like(y)
for i in range(y.shape[0]):
    summed[i, :] = y[i, :] + x
print(summed)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]
2
[[ 4  6  8 10 12]
 [ 9 11 13 15 17]]


37 Write a NumPy program to save a given array to a text file and load it. 

In [241]:
import os
y = np.arange(10, dtype=int).reshape(5,2)
print(y)
header = 'col1 col2'
np.savetxt('array_tmp.txt', y, header=header)
if os.path.exists('array_tmp.txt'):
    x = np.loadtxt('array_tmp.txt')
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
